version: '3.1'

services:

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/var/lib/grafana
    ports: 
      - "3000:3000"

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      
  testingservice:
    image: kennethreitz/httpbin
    ports:
      - "80:80"